### PR TITLE
Ensure that unit tests can be run when WebEnvironment.NONE is used

### LINKED ISSUE #108: Unmatched dependencies between beans
ServerTracingAutoConfiguration has the following dependency:
@ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.SERVLET)
but is also responsible for loading WebTracingProperties.
SkipPatternAutoConfiguration depends on WebTracingProperties being loaded, but is not conditional on Type.SERVLET. Thus, if you run a unittest using webEnvironment = SpringBootTest.WebEnvironment.NONE, Spring will try to instantiate SkipPatternAutoConfiguration, but it will fail since WebTracingProperties is not in the ApplicationContext.

I'm sorry that I don't have a suggested solution, but I don't have the full overview of what is actually required or not in a WebEnvironment.NONE situation.

A reproducer is available at https://github.com/scoof/opentracing-contrib-java-spring-web-reproducer/

### PR DESCRIPTION
**Pull request by geoand**
Fixes #108

### CODE REVIEW

**Comment by geoand** [comment]
@ask4gilles care to review?

**Comment by scoof** [comment]
I'm not sure this is a proper fix. Wouldn't this ignore WebTracingProperties even if the properties were present, when running under WebEnvironment.NONE?

**Comment by geoand** [comment]
Yes, indeed it would. 

Honest question: why would need to set these properties and have all machinery populated when using `WebEnvironment.NONE`?

**Comment by scoof** [comment]
Fair question. However, I don't have enough of an overview to answer that question. I can't say if this will be usable in that context.

**Comment by geoand** [comment]
Me neither :)

Lets see if @ask4gilles has info

**Comment by ask4gilles** [comment]
@geoand I’m on vacation until next week ;)

**Comment by geoand** [comment]
Have fun @ask4gilles !

I'll merge in the meantime and we can reexamine in the future if needed

**Pull request merged**
