### PR TITLE
increase the visibility of shouldFilter.

### PR DESCRIPTION
**Pull request by sijuv**
There could be need to further customize the default shouldFilter implementation, ex you want to exclude traffic based on user agent as in case of bots.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for the contribution.

Can you show a concrete example where you would need this?

Thanks

**Comment by sijuv** [comment]
we have a use case where certain bots hit our production services. These are identified by their user-agent header. We dont want such calls to be traced. 
A sample code would look like this:

    if (Option.ofNullable(request.getHeaders().getFirst(HttpHeaders.USER_AGENT))
        .map(s -> userAgentSkipPattern.matcher(s.toLowerCase()).matches()).orElse(false)) {
      if (LOG.isTraceEnabled()) {
        LOG.trace(
            "Not tracing request " + request + " because it matches user agen skip pattern: " + userAgentSkipPattern);
      }
      return false;
    }

To implement this I would extend the open tracing provided TracingWebFIlter and override the shouldBeTracedMethod.

**Comment by geoand** [comment]
That makes sense, thanks

**Comment by geoand** [comment]
I merged and launched a release of 3.0.1 which should contain the fix if the release goes well

**Pull request merged**
