### PR TITLE
Rename opentracing-spring-web-autoconfigure to opentracing-spring-web-starter

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #75

### CODE REVIEW

**Comment by geoand** [comment]
@pavolloffay Should I start a release, or is there a plan to wait for some other feature to land?

**Comment by pavolloffay** [comment]
go ahead and cut a new one

**Comment by geoand** [comment]
:+1: will do

**Comment by geoand** [comment]
Release is in progress

**Comment by geoand** [comment]
0.3.4 released

**Pull request merged**
