### PR TITLE
Bump Spring/Spring Boot versions

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@gytis @pavolloffay Any idea why the tests are failing?

**Comment by gytis** [comment]
No idea, maybe just try rerunning them.

**Comment by geoand** [comment]
It seems like I can't restart the tests in Travis because I'm not a member of the repo

**Comment by pavolloffay** [comment]
build restarted, I have added you both to maintainers

**Comment by pavolloffay** [comment]
travis keeps failing

**Comment by gytis** [comment]
I guess some API might have changed. That is the reason why the similar update in java-spring-messaging is failing.

**Comment by geoand** [comment]
I think I tried it yesterday and seem to recall that it worked, but I'm not totally sure...

**Comment by pavolloffay** [comment]
any update on this, it has to pass on travis

**Comment by geoand** [comment]
I need to take another look, haven't had the time yet :(

**Comment by geoand** [comment]
I figured out why I couldn't see the failing test locally -> The PR was issued against an old master, against the new master I can see that the tests is failing locally

**Comment by geoand** [comment]
@pavolloffay Fixed the PR :)

**Comment by geoand** [comment]
@pavolloffay Should we go ahead and merge this or are we waiting for more input? Thanks

**Comment by cmoulliard** [comment]
@pavolloffay @objectiser Can you please review, approve it as we are targeting to propductize it this week using SB-1.5.12 ? Can you release it also ?

**Comment by objectiser** [comment]
Release of version 0.3.1 initiated.

**Pull request merged**
