### PR TITLE
Define explicit dependency from auto configs on the tracer auto confi…

### PR DESCRIPTION
**Pull request by objectiser**
…guration to avoid ordering issue where instrumentation not added due to Tracer bean not yet being available. This has been an issue since @ConditionalOnBean(Tracer.class) annotations added in 0.0.10.

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
Problem was found when running the https://github.com/objectiser/opentracing-prometheus-example example - it worked with spring-web 0.0.9, but not 0.0.10 - the issue was introduced with the https://github.com/opentracing-contrib/java-spring-web/commit/82c8f317b791db35d4707ca2e264f6f78b7dd20c commit, introducing the `@ConditionalOnBean(Tracer.class)` annotations.

However the ordering of the autoconfigs seems non-deterministic - the Tracer is always created before the other auto configs in the tests - but not in the example application.

Might be better if the tracer autoconfig is separated out into a framework independent artifact, in case similar dependencies need to be defined for other framework autoconfigs.

**Comment by pavolloffay** [comment]
Do you have error log from https://github.com/objectiser/opentracing-prometheus-example? And what service is failing? Or perhaps both?

**Comment by objectiser** [comment]
Both services are not reporting trace data.

There is no error, simply that the interceptors/filters are not being installed as the `Tracer` does not get created until later.

**Comment by pavolloffay** [comment]
Could you please push a branch somewhere I would like to look at it. I would like to avoid adding `@AutoConfigureAfter(TracerAutoConfiguration.class)` to every auto-config.

**Comment by objectiser** [comment]
Branch: https://github.com/objectiser/opentracing-prometheus-example/tree/updatesw

You can go to folder `simple/accountmgr` and run `mvn spring-boot:run` - you will notice the tracer is created after the filters, so no interceptors added.

**Comment by objectiser** [comment]
Release done - once in maven central I'll update the version in spring-cloud.

**Pull request merged**
