### PR TITLE
Bump to OpenTracing 0.33

### LINKED ISSUE #121: upgrade to opentracing 0.33.0
Please upgrade the libs to use opentracing 0.33.0.  This library currently breaks due to some incompatibilities between 0.32.0 and 0.33.0

### PR DESCRIPTION
**Pull request by geoand**
Resolves #121

### CODE REVIEW

**Comment by geoand** [comment]
Opened the PR as a draft, because one of the dependencies has not yet hit Maven Central

**Comment by geoand** [comment]
`io.opentacing.contrib:opentracing-spring-tracer-configuration-starter:0.3.0` still not on Maven Central so I did a new `0.3.1` release and will update this PR once it's ready

**Comment by geoand** [comment]
@pavolloffay any idea why the releases of `io.opentacing.contrib:opentracing-spring-tracer-configuration-starter` seem to not be making it to Maven Central?

**Comment by pavolloffay** [comment]
First I check the builds https://travis-ci.org/opentracing-contrib/java-spring-tracer-configuration/builds.
It seems that sync to central failed https://travis-ci.org/opentracing-contrib/java-spring-tracer-configuration/builds/576688050#L880

Then I check binray https://bintray.com/opentracing/maven/opentracing-spring-default-tracer-configuration 0.3.1 is there. 

I think you have two options:
1. sync to maven central via binray UI
2. restart the whole process - remove release from binray and restart failed travis job
3. push next release tag to trigger a new release

If you don't have access to binray let me know I will add you.

**Comment by geoand** [comment]
Thanks @pavolloffay.

I guess that you already performed the sync from the Bintray UI? I seem to have access, so I'll do it next time

**Comment by pavolloffay** [comment]
I haven't synced it.

**Comment by geoand** [comment]
OK, I'm not sure what I am supposed to use for `User token key` and `User token password` when using on the `Maven Central` "tab"

**Comment by pavolloffay** [comment]
sonatype user:pass

**Comment by geoand** [comment]
Got it, thanks!

**Comment by mattbroekhuis** [comment]
This builds locally. Can we get it released? I am guessing just re-triggering the build would do it?

**Comment by geoand** [comment]
@pavolloffay Can you please review when you have some time?

**Comment by ttddyy** [comment]
Hi,
I am waiting this version bump to happen as well.

What is the plan here?
Are you going to release new version soon? When would it be?

We are in need for this change, and if it doesn't happen, we need to re-evaluate our upgrades with opentracing API `v0.33`.

So, appreciate merge and release would happen soon.

Thanks,

**Comment by geoand** [comment]
I will merge and do a `3.x` release on Monday unless you have any objections @pavolloffay

**Comment by pavolloffay** [comment]
+1 go ahead

**Comment by geoand** [comment]
I just released version `3.0.0`. It should hopefully be in Maven Central in less than 24h

**Comment by ttddyy** [comment]
@geoand @pavolloffay Thanks!!

**Pull request merged**
